name: Run-Drake-Workflow

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - master
  schedule:
    - cron: "0 0 * * 6"

jobs:

  build-container:
    name: Run workflow
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          credentials_file_path: key.json

      - name: Build image with cache
        id: build_docker
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: $GITHUB_ACTOR
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: ${{ env.REPOSITORY_NAME }}

      - name: Run Targets workflow
        run: docker run -v $(pwd):/home -w /home --name rstudio_container --env R_CONFIG_ACTIVE --env-file <(env | grep SMTP) ${{ steps.build_docker.outputs.FULL_IMAGE_NAME }} make
        env:
          R_CONFIG_ACTIVE: ${{ github.event_name }}
          SMTP_USER: ${{secrets.SMTP_USER}}
          SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}
          SMTP_HOST: ${{secrets.SMTP_HOST}}
          SMTP_PORT: ${{secrets.SMTP_PORT}}

